yellowbox/app/orders/__init__.py
from flask import Blueprint

orders = Blueprint('orders', __name__)

from . import views

yellowbox/app/orders/views.py
from flask import Blueprint, render_template, request, redirect, url_for, session
from . import orders
from app.models import db, Order, Movie, User, Disk, Kiosk
from datetime import datetime
from ..base.views import ReviewForm


@orders.route('/rental_history/<int:movie_id>')
def rental_history(movie_id):
    rentals = db.session.query(
        Order,
        User.id,
        Kiosk.address
    ).join(User, Order.customerId == User.id) \
     .join(Kiosk, Order.movieId == movie_id) \
     .filter(Order.movieId == movie_id).all()

    movie = Movie.query.get_or_404(movie_id)
    return render_template('orders/rental_history.html', rentals=rentals, movie=movie)

@orders.route('/rent_movie/<int:movie_id>', methods=['POST'])
def rent_movie(movie_id):
    customer_id = session.get('userID')  
    
    if not customer_id:
        return redirect(url_for('base.login'))   
     
    disk_id = request.form.get('disk_id')  

    disk = db.session.query(Disk).filter_by(id=disk_id, movieId=movie_id, status=False).first()

    if not disk:
        return redirect(url_for('kiosks.DVDs'))

    new_order = Order(
        movieId=movie_id,
        disk_id=disk.id,
        customerId=customer_id,
        checkoutDate=int(datetime.utcnow().timestamp()),
        returnDate=None, 
    )

    db.session.add(new_order)
    db.session.commit()

    disk.status = True  
    db.session.commit()

    return redirect(url_for('orders.orders'))


@orders.route('/return_movie/<int:order_id>', methods=['POST'])
def return_movie(order_id):
    order = Order.query.get_or_404(order_id)
    order.returnDate = int(datetime.utcnow().timestamp())
    disk = Disk.query.get_or_404(order.disk_id)
    
    disk.status = False

    db.session.commit()
    
    return redirect(url_for('orders.orders', customer_id=order.customerId))

@orders.route('/order_page/<int:order_id>', methods=['GET', 'POST'])
def order_page(order_id):
    order = Order.query.get_or_404(order_id)
    movie = Movie.query.get_or_404(order.movieId)
    form = ReviewForm()

    if form.validate_on_submit():
        order.rating = form.rating.data
        order.review = form.review_text.data
        db.session.commit()
        return redirect(url_for('orders.orders'))

    return render_template('orders/order_page.html', order=order, movie=movie, form=form)

@orders.route('/orders', methods=['GET'])
def orders():
    user_id = request.args.get('user_id')
    if not user_id:
        user_id = session.get('userID')
    if not user_id:
        return redirect('/login')

    orders = Order.query.filter_by(customerId=user_id).all()

    for order in orders:
        order.movie = Movie.query.get(order.movieId)

    return render_template('orders/orders.html', orders=orders)

yellowbox/app/templates/orders/order_page.html
{% extends "base.html" %}

{% block title %}Order Details{% endblock %}

{% block body %}
<div class="container">
    <div class="order-details">
        <h1 class="order-title">Order for {{ movie.title }}</h1>
        <div class="order-info">
            <p><strong>Checkout Date:</strong> {{ order.checkoutDate | datetimeformat if order.checkoutDate else 'N/A'}}
            </p>
            <p>
                <strong>Return Date:</strong> {{ order.returnDate | datetimeformat if order.returnDate else 'Not
                returned' }}
            </p>
        </div>

        <hr>

        <h2 class="review-header">Leave a Review</h2>
        <form method="POST" class="review-form">
            {{ form.hidden_tag() }}

            <div class="form-group">
                <label for="rating" class="form-label">Rating:</label>
                {{ form.rating(class="form-control") }}
            </div>

            <div class="form-group">
                <label for="review_text" class="form-label">Review:</label>
                {{ form.review_text(class="form-control", rows=4, placeholder="Leave your review here...") }}
            </div>

            <div class="form-group">
                {{ form.submit(class="btn button-gold") }}
            </div>
        </form>

        <hr>

        <div class="back-link button-gold">
            <a href="{{ url_for('orders.orders') }}" class="btn btn-secondary">Back to Orders</a>
        </div>
    </div>
</div>

{% endblock %}

yellowbox/app/templates/orders/orders.html
{% extends "base.html" %}

{% block title %}Current Orders - Yellow Bucket{% endblock %}

{% block body %}
<h1>Order History</h1>

<div class="orders-table-container">
    <table class="orders-table">
        <thead>
            <tr>
                <th class="table-header">Order ID</th>
                <th class="table-header">Movie Title</th>
                <th class="table-header">Kiosk Location</th>
                <th class="table-header">Checkout Date</th>
                <th class="table-header">Return Date</th>
                <th class="table-header">Rating</th>
                <th class="table-header">Review</th>
                <th class="table-header"></th>
                <th class="table-header">Return Status</th>

            </tr>
        </thead>
        <tbody>
            {% for order in orders %}
            <tr class="table-row">
                <td class="table-cell">{{ order.id }}</td>
                <td class="table-cell">{{ order.movie.title }}</td>
                <td class="table-cell">{{ order.kioskLocation }}</td>
                <td class="table-cell">{{ order.checkoutDate | datetimeformat if order.checkoutDate else 'N/A' }}
                </td>
                <td class="table-cell">{{ order.returnDate | datetimeformat if order.returnDate else 'Not returned'
                    }}
                </td>
                <td>{{ order.rating if order.rating else 'No rating yet' }}</td>
                <td>{{ order.review if order.review else 'No review yet' }}</td>
                <td>
                    {% if order.rating is none %}
                    <a href="{{ url_for('orders.order_page', order_id=order.id) }}">Leave a Review</a>
                    {% else %}
                    <a href="{{ url_for('orders.order_page', order_id=order.id) }}">Edit Review</a>
                    {% endif %}
                </td>
                <td class="table-cell">
                    {% if not order.returnDate %}
                    <form action="{{ url_for('orders.return_movie', order_id=order.id) }}" method="post">
                        <button class="button-gold" type="submit" class="return-button">Return Movie</button>
                    </form>
                    {% else %}
                    <span class="returned-status">Returned</span>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

yellowbox/app/templates/orders/rental_history.html
{% extends 'base.html' %}

{% block body %}
<h1 class="rental-history-title">Rental History for {{ movie.title }}</h1>


{% if rentals|length > 0 %}
<table class="rental-history-table">
    <thead>
        <tr>
            <th>Kiosk Address</th>
            <th>Checkout Date</th>
            <th>Return Date</th>
        </tr>
    </thead>
    <tbody>
        {% for rental, user_id, address in rentals %}
        <tr>
            <td>{{ address }}</td>
            <td>{{ rental.checkoutDate | datetimeformat }}</td>
            <td>{{ rental.returnDate | datetimeformat }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>No rentals found for this movie.</p>
{% endif %}
{% endblock %}