yellowbox/app/movies/__init__.py
from flask import Blueprint

movies = Blueprint('movies', __name__)

from . import views

yellowbox/app/movies/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from sqlalchemy.sql import func
from datetime import datetime
from . import movies
from app.models import db, Movie, Disk, Kiosk, Order
import json

@movies.route('/view')
def movies_view():
    movie_list = Movie.query.all()
    return render_template('movies/view.html', movies=movie_list)

@movies.route('/search', methods=['GET', 'POST'])
def search():
    movies = []
    if request.method == 'GET':
        title = request.args.get('title')
        run_time_min = request.args.get('run_time_min')
        run_time_max = request.args.get('run_time_max')
        popularity_min = request.args.get('popularity_min')
        popularity_max = request.args.get('popularity_max')
        release_date_min = request.args.get('release_date_min')
        release_date_max = request.args.get('release_date_max')
        rating_min = request.args.get('rating_min')
        rating_max = request.args.get('rating_max')

        query = db.session.query(Movie)

        if title:
            query = query.filter(Movie.title.ilike(f'%{title}%'))
        if run_time_min:
            query = query.filter(Movie.runtime >= int(run_time_min))
        if run_time_max:
            query = query.filter(Movie.runtime <= int(run_time_max))
        if popularity_min:
            query = query.filter(Movie.popularity >= float(popularity_min))
        if popularity_max:
            query = query.filter(Movie.popularity <= float(popularity_max))
        if release_date_min:
            query = query.filter(Movie.release_date >= release_date_min)
        if release_date_max:
            query = query.filter(Movie.release_date <= release_date_max)
        if rating_min:
            query = query.filter(Movie.vote_average >= float(rating_min))
        if rating_max:
            query = query.filter(Movie.vote_average <= float(rating_max))

        movies = query.all()

    return render_template('movies/search.html', movies=movies)

@movies.route('/edit_movie/<int:movie_id>', methods=['GET', 'POST'])
def edit_movie(movie_id):
    movie = Movie.query.get_or_404(movie_id)
    
    if request.method == 'POST':
        movie.title = request.form.get('title')
        movie.overview = request.form.get('overview')
        movie.release_date = request.form.get('release_date')
        movie.budget = request.form.get('budget', type=int)
        movie.revenue = request.form.get('revenue', type=int)
        movie.runtime = request.form.get('runtime', type=int)
        movie.vote_average = request.form.get('vote_average', type=float)
        movie.vote_count = request.form.get('vote_count', type=int)
        movie.genres = request.form.get('genres')
        movie.original_language = request.form.get('original_language')
        movie.poster_path = request.form.get('poster_path')
        movie.belongs_to_collection = request.form.get('belongs_to_collection')
        movie.homepage = request.form.get('homepage')
        movie.imdb_id = request.form.get('imdb_id')
        movie.popularity = request.form.get('popularity', type=float)
        movie.spoken_languages = request.form.get('spoken_languages')
        movie.tagline = request.form.get('tagline')
        movie.production_companies = request.form.get('production_companies')

        db.session.commit()

        return redirect(url_for('movies.movie_detail', movie_id=movie.id))
    
    return render_template('movies/edit_movie.html', movie=movie)


@movies.route('/add_movie', methods=['GET', 'POST'])
def add_movie():
    if request.method == 'POST':
        title = request.form.get('title')
        overview = request.form.get('overview')
        release_date = request.form.get('release_date')
        budget = request.form.get('budget', type=int)
        revenue = request.form.get('revenue', type=int)
        runtime = request.form.get('runtime', type=int)
        vote_average = request.form.get('vote_average', type=float)
        vote_count = request.form.get('vote_count', type=int)
        genres = request.form.get('genres')
        original_language = request.form.get('original_language')
        poster_path = request.form.get('poster_path')
        belongs_to_collection = request.form.get('belongs_to_collection')
        homepage = request.form.get('homepage')
        imdb_id = request.form.get('imdb_id')
        popularity = request.form.get('popularity', type=float)
        spoken_languages = request.form.get('spoken_languages')
        tagline = request.form.get('tagline')
        production_companies = request.form.get('production_companies')

        new_movie = Movie(
            title=title,
            overview=overview,
            release_date=release_date,
            budget=budget,
            revenue=revenue,
            runtime=runtime,
            vote_average=vote_average,
            vote_count=vote_count,
            genres=genres,
            original_language=original_language,
            poster_path=poster_path,
            belongs_to_collection=belongs_to_collection,
            homepage=homepage,
            imdb_id=imdb_id,
            popularity=popularity,
            spoken_languages=spoken_languages,
            tagline=tagline,
            production_companies=production_companies
        )

        db.session.add(new_movie)
        db.session.commit()

        return redirect(url_for('movies.movies'))

    return render_template('movies/add_movie.html')


@movies.route('/collection_items')
def collection_items():
    collection_name = request.args.get('collection_name')
    
    movies = db.session.query(Movie).filter(Movie.belongs_to_collection.contains(collection_name)).all()

    
    return render_template('movies/collection_items.html', movies=movies)
    
    
@movies.route('/movies_search_results', methods=['GET'])
def movies_search_results():
    title = request.args.get('title', '')
    run_time_min = request.args.get('run_time_min', type=int)
    run_time_max = request.args.get('run_time_max', type=int)
    popularity_min = request.args.get('popularity_min', type=float)
    popularity_max = request.args.get('popularity_max', type=float)
    release_date_min = request.args.get('release_date_min', type=str)
    release_date_max = request.args.get('release_date_max', type=str)
    rating_min = request.args.get('rating_min', type=float)
    rating_max = request.args.get('rating_max', type=float)

    query = db.session.query(Movie)

    if title:
        query = query.filter(Movie.title.ilike(f'%{title}%'))
    if run_time_min is not None and run_time_max is not None:
        query = query.filter(Movie.runtime.between(run_time_min, run_time_max))
    elif run_time_min is not None:
        query = query.filter(Movie.runtime >= run_time_min)
    elif run_time_max is not None:
        query = query.filter(Movie.runtime <= run_time_max)
    if popularity_min is not None and popularity_max is not None:
        query = query.filter(Movie.popularity.between(popularity_min, popularity_max))
    elif popularity_min is not None:
        query = query.filter(Movie.popularity >= popularity_min)
    elif popularity_max is not None:
        query = query.filter(Movie.popularity <= popularity_max)
    if release_date_min or release_date_max:
        if release_date_min and release_date_max:
            query = query.filter(Movie.release_date.between(release_date_min, release_date_max))
        elif release_date_min:
            query = query.filter(Movie.release_date >= release_date_min)
        elif release_date_max:
            query = query.filter(Movie.release_date <= release_date_max)
    if rating_min is not None and rating_max is not None:
        query = query.filter(Movie.vote_average.between(rating_min, rating_max))
    elif rating_min is not None:
        query = query.filter(Movie.vote_average >= rating_min)
    elif rating_max is not None:
        query = query.filter(Movie.vote_average <= rating_max)

    movies = query.all()

    return render_template('movies/movies_search_results.html', movies=movies)


@movies.route('/movie/<int:movie_id>')
def movie_detail(movie_id):
    movie = db.session.query(Movie).get(movie_id)
    
    avg_rating = db.session.query(func.avg(Order.rating)).filter(Order.movieId == movie_id).scalar()
    avg_rating = round(avg_rating, 2) if avg_rating else "No ratings yet"
    
    reviews = db.session.query(Order).filter(Order.movieId == movie_id).all()
    print(reviews)

    available_disks = db.session.query(Disk, Kiosk.address).join(Kiosk, Kiosk.id == Disk.kiosk_id).filter(Disk.movieId == movie_id, Disk.status == False).all()

    return render_template('movies/movie_detail.html', movie=movie, avg_rating=avg_rating, available_disks=available_disks, reviews = reviews)


@movies.app_template_filter('datetimeformat')
def datetimeformat(value):
    if value:
        return datetime.utcfromtimestamp(value).strftime('%Y-%m-%d %H:%M:%S')
    return 'N/A'

yellowbox/app/templates/movies/add_movie.html
{% extends "base.html" %}

{% block title %}Add Movie - Yellow Bucket{% endblock %}

{% block body %}
<button onclick="history.back()">Back to previous page</button>
<h1 class="title">Add Movie</h1>

<form action="{{ url_for('movies.add_movie') }}" method="post">
    <label for="title">Title:</label>
    <input type="text" id="title" name="title" required>

    <label for="overview">Overview:</label>
    <textarea id="overview" name="overview" required></textarea>

    <label for="release_date">Release Date:</label>
    <input type="date" id="release_date" name="release_date" required>

    <label for="budget">Budget:</label>
    <input type="number" id="budget" name="budget">

    <label for="revenue">Revenue:</label>
    <input type="number" id="revenue" name="revenue">

    <label for="runtime">Runtime (minutes):</label>
    <input type="number" id="runtime" name="runtime">

    <label for="vote_average">Vote Average:</label>
    <input type="number" id="vote_average" name="vote_average" step="0.1" min="0" max="10">

    <label for="vote_count">Vote Count:</label>
    <input type="number" id="vote_count" name="vote_count">

    <label for="genres">Genres (comma-separated):</label>
    <input type="text" id="genres" name="genres">

    <label for="original_language">Original Language:</label>
    <input type="text" id="original_language" name="original_language" required>

    <label for="poster_path">Poster Path:</label>
    <input type="text" id="poster_path" name="poster_path">

    <label for="belongs_to_collection">Belongs To Collection:</label>
    <input type="text" id="belongs_to_collection" name="belongs_to_collection">

    <label for="homepage">Homepage:</label>
    <input type="text" id="homepage" name="homepage">

    <label for="imdb_id">IMDB ID:</label>
    <input type="text" id="imdb_id" name="imdb_id">

    <label for="popularity">Popularity:</label>
    <input type="number" id="popularity" name="popularity" step="0.1">

    <label for="spoken_languages">Spoken Languages (comma-separated):</label>
    <input type="text" id="spoken_languages" name="spoken_languages">

    <label for="tagline">Tagline:</label>
    <input type="text" id="tagline" name="tagline">

    <label for="production_companies">Production Companies (comma-separated):</label>
    <input type="text" id="production_companies" name="production_companies">

    <button type="submit">Add Movie</button>
</form>

{% endblock %}

yellowbox/app/templates/movies/collection_items.html
{% extends "base.html" %}

{% block title %}Movie List - Yellow Bucket{% endblock %}

{% block body %}
<section class="section">
    <div class="container">
        <h1 class="title">Welcome to Yellow Bucket!</h1>

        <h2>Collection Movies</h2>
        <br />
        <ul class="movie-grid">
            {% for movie in movies %}
            <li class="movie-item">
                <a href="{{ url_for('movies.movie_detail', movie_id=movie.id) }}">{{ movie.title }}</a><a
                    href="{{ url_for('movies.movie_detail', movie_id=movie.id) }}">
                    <img src="https://image.tmdb.org/t/p/original{{ movie.poster_path }}"
                        alt="{{ movie.title }} poster"></a>
            </li>
            {% endfor %}
        </ul>
        <br />
        <button onclick="history.back()">Back to previous page</button>
    </div>
</section>
{% endblock %}

yellowbox/app/templates/movies/edit_movie.html
{% extends "base.html" %}

{% block title %}Edit {{ movie.title }} - Yellow Bucket{% endblock %}

{% block body %}
<button onclick="history.back()">Back to previous page</button>
<h1>Edit Movie: {{ movie.title }}</h1>
<form action="{{ url_for('movies.edit_movie', movie_id=movie.id) }}" method="post">
    <label for="title">Title:</label>
    <input type="text" id="title" name="title" value="{{ movie.title }}" required>

    <label for="overview">Overview:</label>
    <textarea id="overview" name="overview">{{ movie.overview }}</textarea>

    <label for="release_date">Release Date:</label>
    <input type="text" id="release_date" name="release_date" value="{{ movie.release_date }}">

    <label for="budget">Budget:</label>
    <input type="number" id="budget" name="budget" value="{{ movie.budget }}">

    <label for="revenue">Revenue:</label>
    <input type="number" id="revenue" name="revenue" value="{{ movie.revenue }}">

    <label for="runtime">Runtime (minutes):</label>
    <input type="number" id="runtime" name="runtime" value="{{ movie.runtime }}">

    <label for="vote_average">Rating:</label>
    <input type="number" id="vote_average" name="vote_average" step="0.1" value="{{ movie.vote_average }}">

    <label for="vote_count">Vote Count:</label>
    <input type="number" id="vote_count" name="vote_count" value="{{ movie.vote_count }}">

    <label for="genres">Genres:</label>
    <input type="text" id="genres" name="genres" value="{{ movie.genres }}">

    <label for="original_language">Original Language:</label>
    <input type="text" id="original_language" name="original_language" value="{{ movie.original_language }}">

    <label for="poster_path">Poster Path:</label>
    <input type="text" id="poster_path" name="poster_path" value="{{ movie.poster_path }}">

    <label for="belongs_to_collection">Collection:</label>
    <input type="text" id="belongs_to_collection" name="belongs_to_collection"
        value="{{ movie.belongs_to_collection }}">

    <label for="homepage">Homepage:</label>
    <input type="url" id="homepage" name="homepage" value="{{ movie.homepage }}">

    <label for="imdb_id">IMDB ID:</label>
    <input type="text" id="imdb_id" name="imdb_id" value="{{ movie.imdb_id }}">

    <label for="popularity">Popularity:</label>
    <input type="number" id="popularity" name="popularity" step="0.01" value="{{ movie.popularity }}">

    <label for="spoken_languages">Spoken Languages:</label>
    <input type="text" id="spoken_languages" name="spoken_languages" value="{{ movie.spoken_languages }}">

    <label for="tagline">Tagline:</label>
    <textarea id="tagline" name="tagline">{{ movie.tagline }}</textarea>

    <label for="production_companies">Production Companies:</label>
    <input type="text" id="production_companies" name="production_companies" value="{{ movie.production_companies }}">

    <button type="submit">Save Changes</button>
</form>
{% endblock %}

yellowbox/app/templates/movies/movie_detail.html
{% extends "base.html" %}

{% block title %}{{ movie.title }} - Yellow Bucket{% endblock %}

{% block body %}
<button class="button-gold" onclick="history.back()">Back to previous page</button>
<section class="section">
    <div class="container">
        <div class="movie-details">
            <img src="https://image.tmdb.org/t/p/w342{{ movie.poster_path }}" alt="{{ movie.title }}" loading="lazy">

            <div class="movie-info">
                <h1 class="title">{{ movie.title }}</h1>
                <p><strong>Overview:</strong> {{ movie.overview }}</p>
                <p><strong>Release Date:</strong> {{ movie.release_date }}</p>
                <p><strong>TMDB Rating:</strong> {{ movie.vote_average }}</p>
                <p><strong>Average Customer Rating:</strong> {{ avg_rating }}</p>
                <a href="{{ url_for('movies.edit_movie', movie_id=movie.id) }}">
                    <button class="button-gold">Edit Movie</button>
                </a>
                <br><br>
                <a class="button-gold" href="{{ url_for('orders.rental_history', movie_id=movie.id) }}">View Rental
                    History</a>
            </div>
        </div>

        <hr>

        <div class="rent-and-reviews">
            <div class="rent-section">
                <h2>Rent This Movie</h2>
                {% if available_disks %}
                <form action="{{ url_for('orders.rent_movie', movie_id=movie.id) }}" method="post">

                    <label for="disk_id">Select Disk:</label>
                    <select id="disk_id" name="disk_id" required>
                        {% for disk, kiosk_location in available_disks %}
                        <option value="{{ disk.id }}">
                            Disk {{ disk.serialNumber }} (Kiosk Location: {{ kiosk_location }})
                        </option>
                        {% endfor %}
                    </select>

                    <button class="button-gold" type="submit">Rent Movie</button>
                </form>
                {% else %}
                <p>No available disks for this movie at the moment.</p>
                {% endif %}
            </div>

            <div class="reviews-section">
                <h2>User Reviews</h2>
                <div class="reviews-list">
                    {% if reviews %}
                    {% for order in reviews %}
                    <div class="review">
                        <p>{{ order.review }}</p>
                    </div>
                    {% endfor %}
                    {% else %}
                    <p>No reviews for this movie yet.</p>
                    {% endif %}
                </div>
            </div>
        </div>

</section>
{% endblock %}

yellowbox/app/templates/movies/movies_search_results.html
{% extends "base.html" %}

{% block title %}Search Results - Yellow Bucket{% endblock %}

{% block body %}
<button onclick="history.back()">Back to previous page</button>
<h1 class="title">Search Results</h1>

<ul class="movie-grid">
    {% for movie in movies %}
    <li class="movie-item">
        <a href="{{ url_for('movies.movie_detail', movie_id=movie.id) }}">
            <img src="https://image.tmdb.org/t/p/w154{{ movie.poster_path }}" alt="{{ movie.title }} poster">
            <p>{{ movie.title }}</p>
        </a>
    </li>
    {% endfor %}
</ul>

<button onclick="history.back()">Back to previous page</button>
{% endblock %}

yellowbox/app/templates/movies/search.html
{% extends "base.html" %}

{% block title %}Movie Search - Yellow Bucket{% endblock %}

{% block body %}
<section class="section">
    <div class="container">
        <h1 class="title has-text-centered">Search Movies</h1>

        <form method="GET" action="{{ url_for('movies.search') }}" class="box">
            <div class="field">
                <label for="title" class="label">Title:</label>
                <div class="control">
                    <input type="text" id="title" name="title" class="input" placeholder="Search by title..."
                        autocomplete="off">
                </div>
            </div>

            <div class="field">
                <label for="run_time_min" class="label">Runtime Min:</label>
                <div class="control">
                    <input type="number" id="run_time_min" name="run_time_min" class="input">
                </div>
            </div>

            <div class="field">
                <label for="run_time_max" class="label">Runtime Max:</label>
                <div class="control">
                    <input type="number" id="run_time_max" name="run_time_max" class="input">
                </div>
            </div>

            <div class="field">
                <label for="popularity_min" class="label">Popularity Min:</label>
                <div class="control">
                    <input type="number" step="0.1" id="popularity_min" name="popularity_min" class="input">
                </div>
            </div>

            <div class="field">
                <label for="popularity_max" class="label">Popularity Max:</label>
                <div class="control">
                    <input type="number" step="0.1" id="popularity_max" name="popularity_max" class="input">
                </div>
            </div>

            <div class="field">
                <label for="release_date_min" class="label">Release Date From:</label>
                <div class="control">
                    <input type="date" id="release_date_min" name="release_date_min" class="input">
                </div>
            </div>

            <div class="field">
                <label for="release_date_max" class="label">Release Date To:</label>
                <div class="control">
                    <input type="date" id="release_date_max" name="release_date_max" class="input">
                </div>
            </div>

            <div class="field">
                <label for="rating_min" class="label">Rating Min:</label>
                <div class="control">
                    <input type="number" step="0.1" id="rating_min" name="rating_min" class="input">
                </div>
            </div>

            <div class="field">
                <label for="rating_max" class="label">Rating Max:</label>
                <div class="control">
                    <input type="number" step="0.1" id="rating_max" name="rating_max" class="input">
                </div>
            </div>

            <div class="field is-grouped">
                <div class="control">
                    <button type="submit" class="button-gold">Search</button>
                </div>
            </div>
        </form>

        <div class="title is-4 has-text-centered"><strong>Search Results:</strong></div>
        <ul class="movie-grid">
            {% for movie in movies %}
            <li class="movie-item">
                <a href="{{ url_for('movies.movie_detail', movie_id=movie.id) }}">
                    <img src="https://image.tmdb.org/t/p/w154{{ movie.poster_path }}" alt="{{ movie.title }} poster"
                        class="movie-poster">
                    <div class="movie-info">
                        <p class="title is-5">{{ movie.title }}</p>
                        <p>Average Rating: {{ movie.vote_average }}</p>
                    </div>
                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</section>

{% endblock %}

yellowbox/app/templates/movies/view.html
{% extends "base.html" %}

{% block title %}Movie List - Yellow Bucket{% endblock %}

{% block body %}
<section class="section">
    <div class="container">

        <div class="buttons">
            <a href="{{ url_for('movies.search') }}" class="button-gold">
                Search Movies
            </a>
        </div>

        <h1 class="title">All Movies</h1>


        <ul class="movie-grid">
            {% for movie in movies %}
            <li class="movie-item">
                <a href="{{ url_for('movies.movie_detail', movie_id=movie.id) }}">
                    <img src="https://image.tmdb.org/t/p/w154{{ movie.poster_path }}" alt="{{ movie.title }} poster">
                    <p class="movie-title">{{ movie.title }}</p>

                </a>
            </li>
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock %}